name: iOS Build (PR)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

concurrency:
  group: ios-pr-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-14
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'

      - name: Show Xcode version
        run: xcodebuild -version

      - name: List project schemes (diagnostics)
        run: xcodebuild -list -project Taspla.xcodeproj

      - name: Resolve package dependencies
        run: xcodebuild -resolvePackageDependencies -project Taspla.xcodeproj

      - name: Build (Debug, iOS Simulator)
        run: |
          set -eo pipefail
          xcodebuild \
            -project Taspla.xcodeproj \
            -scheme Taspla \
            -configuration Debug \
            -destination 'generic/platform=iOS Simulator' \
            clean build

